version: "3.9"
services:
  app_nginx:
    container_name: app_nginx
    build:
      context: ./docker/nginx
    ports:
      - 8080:80
    environment:
      PHP_FPM_IP: app_php
      PHP_FPM_PORT: 9000
    volumes:
      - ./app:/var/www/app
    links:
      - app_php
    working_dir: /var/www/app

  app_php:
    container_name: app_php
    build:
      context: ./docker/php
    volumes:
      - ./app:/var/www/app

  app_db:
    container_name: app_db
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
