version: "3.9"
services:

  graph_nginx:
    build:
      context: ./docker/nginx
    ports:
      - 8080:80
    environment:
      PHP_FPM_IP: graph_php
      PHP_FPM_PORT: 9000
    volumes:
      - ./app:/var/www/app
    links:
      - graph_php
    working_dir: /var/www/app

  graph_php:
    build:
      context: ./docker/php
    environment:
      DATABASE_URL: ""
    volumes:
      - ./app:/var/www/app
