jms_serializer:
  metadata:
    debug: true
    file_cache:
      dir: "%kernel.cache_dir%/serializer"
    auto_detection: true
    directories:
      App:
        namespace_prefix: 'App\Application\QueryModel\Book'
        path: '%kernel.project_dir%/src/Application/QueryModel/Book'