nelmio_api_doc:
  models: { use_jms: false }
  documentation:
    servers:
      - url: http://localhost:8080
        description: API over HTTP
    info:
      title: Api Document App Example
      description: This is an awesome app!
      version: 1.0.0
  areas:
    path_patterns:
      - ^/api